/**
 * A SMALL PDF WRITER: text, rules and links on A4 pages, in an embedded font.
 *
 * WHY NOT A LIBRARY. The one PDF this app produces is a text document (the
 * moderation statement of reasons, lib/moderation/statement.ts), and it runs
 * inside the Cloudflare Worker that serves every other request. pdf-lib plus
 * the fontkit it needs for a non-standard font is over a megabyte of bundle for
 * that, and the standard PDF fonts cannot print Czech, Polish or Slovak. This
 * writes exactly what the statement uses: one embedded TrueType font in two
 * weights (font-data.ts, generated by scripts/build-pdf-font.py), word-wrapped
 * paragraphs, horizontal rules, link annotations, and a footer per page.
 *
 * TEXT IS REAL TEXT. Each font carries a ToUnicode map, so what a reader
 * copies, searches or hears from a screen reader is the words, not glyph ids.
 * The document declares its language and title for the same reason.
 *
 * Pure: no I/O, no Node or Worker APIs beyond `atob`, deterministic for a
 * given input and creation date (which is what lets tests compare output).
 */

/** One embedded font, as scripts/build-pdf-font.py emits it. */
export type EmbeddedFont = {
  postscriptName: string;
  unitsPerEm: number;
  ascent: number;
  descent: number;
  capHeight: number;
  bbox: readonly [number, number, number, number];
  notdefWidth: number;
  /** Flat triples: codepoint, glyph id, advance width in font units. */
  glyphs: readonly number[];
  /** Byte length of the TrueType file before deflating (PDF /Length1). */
  length: number;
  /** The TrueType file, zlib-deflated, base64. */
  deflated: string;
};

export type FontWeight = "regular" | "bold";

/** Greys the statement uses, as PDF fill values (0 = black, 1 = white). */
export const PDF_INK = 0.09;
export const PDF_MUTED = 0.4;
export const PDF_RULE = 0.82;

/** A4 in points, and the margins every page shares. */
const PAGE_WIDTH = 595.28;
const PAGE_HEIGHT = 841.89;
const MARGIN_X = 56;
const MARGIN_TOP = 64;
const MARGIN_BOTTOM = 72;
const FOOTER_BASELINE = 40;
const LINE_HEIGHT = 1.45;

/** Where text may run on a page. */
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN_X * 2;

/** `codepoint` is the character the glyph DRAWS, which is what the text layer
 *  maps it back to: "?" for a character the font lacks, never the lost one. */
type Glyph = { gid: number; width: number; codepoint: number };

const BULLET = String.fromCodePoint(0x2022);

/** Glyph lookup and measurement for one font. Widths are in 1/1000 em. */
class FontFace {
  readonly used = new Map<number, number>();
  private readonly byCodepoint = new Map<number, Glyph>();
  private readonly widthByGid = new Map<number, number>();
  private readonly fallback: Glyph;
  readonly font: EmbeddedFont;

  constructor(font: EmbeddedFont) {
    this.font = font;
    const scale = 1000 / font.unitsPerEm;
    for (let i = 0; i + 2 < font.glyphs.length; i += 3) {
      const glyph = {
        gid: font.glyphs[i + 1]!,
        width: Math.round(font.glyphs[i + 2]! * scale),
        codepoint: font.glyphs[i]!,
      };
      this.byCodepoint.set(font.glyphs[i]!, glyph);
      this.widthByGid.set(glyph.gid, glyph.width);
    }
    this.fallback = this.byCodepoint.get(0x3f) ?? {
      gid: 0,
      width: Math.round(font.notdefWidth * scale),
      codepoint: 0x3f,
    };
  }

  /** The glyph for one character: itself, its unaccented base letter, or "?". */
  glyph(char: string): Glyph {
    const direct = this.byCodepoint.get(char.codePointAt(0)!);
    if (direct) return direct;
    const base = char.normalize("NFD").codePointAt(0);
    return (base !== undefined && this.byCodepoint.get(base)) || this.fallback;
  }

  /** Width of `text` at `size` points. */
  measure(text: string, size: number): number {
    let total = 0;
    for (const char of text) total += this.glyph(char).width;
    return (total * size) / 1000;
  }

  /** `text` as a hex string of 2-byte glyph ids, recording what was used. */
  encode(text: string): string {
    let hex = "";
    for (const char of text) {
      const glyph = this.glyph(char);
      this.used.set(glyph.gid, glyph.codepoint);
      hex += glyph.gid.toString(16).padStart(4, "0");
    }
    return hex;
  }

  widthOf(gid: number): number {
    return this.widthByGid.get(gid) ?? this.fallback.width;
  }
}

type TextRun = {
  kind: "text";
  x: number;
  y: number;
  size: number;
  weight: FontWeight;
  grey: number;
  text: string;
};
type Rule = { kind: "rule"; y: number; grey: number };
type Link = { kind: "link"; x: number; y: number; width: number; height: number; url: string };
type Op = TextRun | Rule | Link;

export type TextOptions = {
  size?: number;
  weight?: FontWeight;
  grey?: number;
  /** Space above, in points. */
  before?: number;
  /** Space below, in points. */
  after?: number;
  /** Indent from the left margin, in points. */
  indent?: number;
  /** Makes every line of the paragraph a link to this URL. */
  url?: string;
};

export type PdfMetadata = {
  title: string;
  /** BCP 47 tag of the document's language, e.g. "cs" or "pt-PT". */
  lang: string;
  author?: string;
  subject?: string;
  /** Fixed in tests; defaults to now. */
  createdAt?: Date;
};

/**
 * Collects content top to bottom, breaking pages as it goes, then serialises.
 *
 *   const pdf = new PdfDocument({ title, lang }, { regular, bold });
 *   pdf.text("Heading", { size: 18, weight: "bold" });
 *   pdf.text(paragraph);
 *   const bytes = pdf.render((page, total) => `${page} / ${total}`);
 */
export class PdfDocument {
  private readonly faces: Record<FontWeight, FontFace>;
  private readonly pages: Op[][] = [[]];
  private y = PAGE_HEIGHT - MARGIN_TOP;
  private readonly meta: PdfMetadata;

  constructor(meta: PdfMetadata, fonts: Record<FontWeight, EmbeddedFont>) {
    this.meta = meta;
    this.faces = { regular: new FontFace(fonts.regular), bold: new FontFace(fonts.bold) };
  }

  /** A paragraph, word-wrapped to the page. `\n` starts a new line. */
  text(value: string, options: TextOptions = {}): this {
    const size = options.size ?? 10;
    const weight = options.weight ?? "regular";
    const grey = options.grey ?? PDF_INK;
    const indent = options.indent ?? 0;
    const lineHeight = size * LINE_HEIGHT;
    const lines = this.wrap(clean(value), size, weight, CONTENT_WIDTH - indent);

    this.y -= options.before ?? 0;
    for (const line of lines) {
      this.ensure(lineHeight);
      this.y -= size;
      const x = MARGIN_X + indent;
      this.page.push({ kind: "text", x, y: this.y, size, weight, grey, text: line });
      if (options.url && line) {
        this.page.push({
          kind: "link",
          x,
          y: this.y - size * 0.25,
          width: this.faces[weight].measure(line, size),
          height: size * 1.2,
          url: options.url,
        });
      }
      this.y -= lineHeight - size;
    }
    this.y -= options.after ?? 0;
    return this;
  }

  /** A label above its value, the shape every fact in the statement takes. */
  field(label: string, value: string, options: { url?: string } = {}): this {
    this.keepTogether(40);
    this.text(label, { size: 8.5, weight: "bold", grey: PDF_MUTED, before: 6 });
    return this.text(value, { size: 10, after: 2, url: options.url });
  }

  /** Bulleted lines, each wrapped under its own bullet. */
  bullets(items: readonly string[], options: TextOptions = {}): this {
    const size = options.size ?? 10;
    const left = options.indent ?? 0;
    for (const item of items) {
      // Room for the first line is made HERE, so the paragraph below cannot
      // break the page before it: its first line is the op pushed next.
      this.ensure(size * LINE_HEIGHT);
      const page = this.page;
      const first = page.length;
      this.text(item, { ...options, size, indent: left + 12, before: 0 });
      const line = page[first];
      if (line?.kind === "text") page.push({ ...line, x: MARGIN_X + left, text: BULLET });
    }
    return this;
  }

  /** A thin full-width line. */
  rule(options: { before?: number; after?: number } = {}): this {
    this.y -= options.before ?? 8;
    this.ensure(1);
    this.page.push({ kind: "rule", y: this.y, grey: PDF_RULE });
    this.y -= options.after ?? 8;
    return this;
  }

  /** Starts a new page unless `height` points still fit on this one. */
  keepTogether(height: number): this {
    this.ensure(height);
    return this;
  }

  /** The finished file. `footer` is drawn on every page. */
  render(footer?: (page: number, total: number) => string): Uint8Array {
    const total = this.pages.length;
    if (footer) {
      this.pages.forEach((ops, index) => {
        ops.push({
          kind: "text",
          x: MARGIN_X,
          y: FOOTER_BASELINE,
          size: 8,
          weight: "regular",
          grey: PDF_MUTED,
          text: clean(footer(index + 1, total)),
        });
      });
    }
    return serialise(this.meta, this.pages, this.faces);
  }

  private get page(): Op[] {
    return this.pages[this.pages.length - 1]!;
  }

  private ensure(height: number): void {
    if (this.y - height >= MARGIN_BOTTOM) return;
    this.pages.push([]);
    this.y = PAGE_HEIGHT - MARGIN_TOP;
  }

  /** Greedy word wrap; a word wider than the line is broken by character. */
  private wrap(value: string, size: number, weight: FontWeight, width: number): string[] {
    const face = this.faces[weight];
    const out: string[] = [];
    for (const paragraph of value.split("\n")) {
      let line = "";
      for (const word of paragraph.split(" ")) {
        const candidate = line ? `${line} ${word}` : word;
        if (face.measure(candidate, size) <= width) {
          line = candidate;
          continue;
        }
        if (line) out.push(line);
        line = "";
        let rest = word;
        while (face.measure(rest, size) > width) {
          let cut = rest.length - 1;
          while (cut > 1 && face.measure(rest.slice(0, cut), size) > width) cut -= 1;
          out.push(rest.slice(0, cut));
          rest = rest.slice(cut);
        }
        line = rest;
      }
      out.push(line);
    }
    return out;
  }
}

/** NFC, tabs as spaces, and no control characters but the newline. */
function clean(value: string): string {
  return value
    .normalize("NFC")
    .replace(/\r\n?/g, "\n")
    .replace(/\t/g, " ")
    .replace(/[\u0000-\u0009\u000b-\u001f\u007f]/g, "");
}

// ── Serialisation ─────────────────────────────────────────────────────────

const encoder = new TextEncoder();

/** Accumulates the file and remembers where each object starts, for xref. */
class Writer {
  private readonly chunks: Uint8Array[] = [];
  private size = 0;
  readonly offsets: number[] = [];

  write(data: string | Uint8Array): void {
    const bytes = typeof data === "string" ? encoder.encode(data) : data;
    this.chunks.push(bytes);
    this.size += bytes.length;
  }

  object(id: number, body: string): void {
    this.offsets[id] = this.size;
    this.write(`${id} 0 obj\n${body}\nendobj\n`);
  }

  stream(id: number, dict: string, data: Uint8Array): void {
    this.offsets[id] = this.size;
    this.write(`${id} 0 obj\n<< ${dict} /Length ${data.length} >>\nstream\n`);
    this.write(data);
    this.write("\nendstream\nendobj\n");
  }

  get position(): number {
    return this.size;
  }

  bytes(): Uint8Array {
    const out = new Uint8Array(this.size);
    let offset = 0;
    for (const chunk of this.chunks) {
      out.set(chunk, offset);
      offset += chunk.length;
    }
    return out;
  }
}

/** A number as PDF writes it: at most two decimals, no trailing zeros. */
function num(value: number): string {
  return String(Math.round(value * 100) / 100);
}

/** A text string for the Info dictionary: UTF-16BE with a byte order mark. */
function textString(value: string): string {
  let hex = "FEFF";
  for (let i = 0; i < value.length; i += 1) {
    hex += value.charCodeAt(i).toString(16).padStart(4, "0").toUpperCase();
  }
  return `<${hex}>`;
}

/** A literal string of ASCII, escaped. Only ever given URLs and tags. */
function literal(value: string): string {
  const ascii = value.replace(/[^\x20-\x7e]/g, (char) => encodeURIComponent(char));
  return `(${ascii.replace(/[\\()]/g, (char) => `\\${char}`)})`;
}

function pdfDate(date: Date): string {
  const pad = (n: number) => String(n).padStart(2, "0");
  return (
    `D:${date.getUTCFullYear()}${pad(date.getUTCMonth() + 1)}${pad(date.getUTCDate())}` +
    `${pad(date.getUTCHours())}${pad(date.getUTCMinutes())}${pad(date.getUTCSeconds())}Z`
  );
}

function base64Bytes(value: string): Uint8Array {
  const binary = atob(value);
  const out = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i += 1) out[i] = binary.charCodeAt(i);
  return out;
}

/** A six-letter subset tag, stable per font, as PDF expects on a subset. */
function subsetTag(name: string): string {
  let hash = 0;
  for (const char of name) hash = (hash * 31 + char.charCodeAt(0)) >>> 0;
  let tag = "";
  for (let i = 0; i < 6; i += 1) {
    tag += String.fromCharCode(65 + (hash % 26));
    hash = Math.floor(hash / 26) + i * 7;
  }
  return tag;
}

function toUnicodeCMap(used: Map<number, number>): Uint8Array {
  const entries = [...used.entries()].sort((a, b) => a[0] - b[0]);
  const lines: string[] = [];
  // bfchar blocks hold at most 100 entries each.
  for (let i = 0; i < entries.length; i += 100) {
    const block = entries.slice(i, i + 100);
    lines.push(`${block.length} beginbfchar`);
    for (const [gid, codepoint] of block) {
      const utf16 = String.fromCodePoint(codepoint);
      let hex = "";
      for (let j = 0; j < utf16.length; j += 1) {
        hex += utf16.charCodeAt(j).toString(16).padStart(4, "0");
      }
      lines.push(`<${gid.toString(16).padStart(4, "0")}> <${hex}>`);
    }
    lines.push("endbfchar");
  }
  return encoder.encode(
    [
      "/CIDInit /ProcSet findresource begin",
      "12 dict begin",
      "begincmap",
      "/CIDSystemInfo << /Registry (Adobe) /Ordering (UCS) /Supplement 0 >> def",
      "/CMapName /Adobe-Identity-UCS def",
      "/CMapType 2 def",
      "1 begincodespacerange",
      "<0000> <FFFF>",
      "endcodespacerange",
      ...lines,
      "endcmap",
      "CMapName currentdict /CMap defineresource pop",
      "end",
      "end",
    ].join("\n"),
  );
}

function contentStream(ops: Op[], faces: Record<FontWeight, FontFace>): Uint8Array {
  const out: string[] = [];
  for (const op of ops) {
    if (op.kind === "text") {
      if (!op.text) continue;
      const font = op.weight === "bold" ? "/F2" : "/F1";
      out.push(
        `BT ${font} ${num(op.size)} Tf ${num(op.grey)} g ${num(op.x)} ${num(op.y)} Td <${faces[
          op.weight
        ].encode(op.text)}> Tj ET`,
      );
    } else if (op.kind === "rule") {
      out.push(
        `${num(op.grey)} G 0.6 w ${num(MARGIN_X)} ${num(op.y)} m ${num(
          PAGE_WIDTH - MARGIN_X,
        )} ${num(op.y)} l S`,
      );
    }
  }
  return encoder.encode(out.join("\n"));
}

function serialise(
  meta: PdfMetadata,
  pages: Op[][],
  faces: Record<FontWeight, FontFace>,
): Uint8Array {
  // Content first: encoding the text is what records which glyphs each font
  // needs, and the font objects below are written from that record.
  const contents = pages.map((ops) => contentStream(ops, faces));

  const w = new Writer();
  // The comment line of high bytes marks the file as binary for transfer tools.
  w.write("%PDF-1.7\n");
  w.write(new Uint8Array([0x25, 0xe2, 0xe3, 0xcf, 0xd3, 0x0a]));

  // Fixed ids: 1 catalog, 2 page tree, 3 info, then 5 per font, then pages.
  const CATALOG = 1;
  const PAGES = 2;
  const INFO = 3;
  const fontIds: Record<FontWeight, number> = { regular: 4, bold: 9 };
  const firstPage = 14;
  const pageIds = pages.map((_, index) => firstPage + index * 2);

  w.object(
    CATALOG,
    `<< /Type /Catalog /Pages ${PAGES} 0 R /Lang ${literal(meta.lang)} /ViewerPreferences << /DisplayDocTitle true >> >>`,
  );
  w.object(
    PAGES,
    `<< /Type /Pages /Kids [${pageIds.map((id) => `${id} 0 R`).join(" ")}] /Count ${pages.length} >>`,
  );
  const created = pdfDate(meta.createdAt ?? new Date());
  w.object(
    INFO,
    `<< /Title ${textString(meta.title)}${meta.author ? ` /Author ${textString(meta.author)}` : ""}${
      meta.subject ? ` /Subject ${textString(meta.subject)}` : ""
    } /Producer ${textString("Square Share")} /CreationDate (${created}) >>`,
  );

  for (const weight of ["regular", "bold"] as const) {
    const face = faces[weight];
    const { font } = face;
    const id = fontIds[weight];
    const [type0, cid, descriptor, file, cmap] = [id, id + 1, id + 2, id + 3, id + 4];
    const name = `${subsetTag(font.postscriptName)}+${font.postscriptName}`;
    const scale = 1000 / font.unitsPerEm;
    const gids = [...face.used.keys()].sort((a, b) => a - b);
    const widths = gids.map((gid) => `${gid} [${face.widthOf(gid)}]`).join(" ");

    w.object(
      type0,
      `<< /Type /Font /Subtype /Type0 /BaseFont /${name} /Encoding /Identity-H /DescendantFonts [${cid} 0 R] /ToUnicode ${cmap} 0 R >>`,
    );
    w.object(
      cid,
      `<< /Type /Font /Subtype /CIDFontType2 /BaseFont /${name} /CIDSystemInfo << /Registry (Adobe) /Ordering (Identity) /Supplement 0 >> /FontDescriptor ${descriptor} 0 R /DW ${Math.round(
        font.notdefWidth * scale,
      )} /W [${widths}] /CIDToGIDMap /Identity >>`,
    );
    w.object(
      descriptor,
      `<< /Type /FontDescriptor /FontName /${name} /Flags 32 /FontBBox [${font.bbox
        .map((value) => Math.round(value * scale))
        .join(" ")}] /ItalicAngle 0 /Ascent ${Math.round(font.ascent * scale)} /Descent ${Math.round(
        font.descent * scale,
      )} /CapHeight ${Math.round(font.capHeight * scale)} /StemV ${
        weight === "bold" ? 120 : 80
      } /FontFile2 ${file} 0 R >>`,
    );
    w.stream(file, `/Filter /FlateDecode /Length1 ${font.length}`, base64Bytes(font.deflated));
    w.stream(cmap, "", toUnicodeCMap(face.used));
  }

  pages.forEach((ops, index) => {
    const pageId = pageIds[index]!;
    const links = ops.filter((op): op is Link => op.kind === "link");
    const annots = links.length
      ? ` /Annots [${links
          .map(
            (link) =>
              `<< /Type /Annot /Subtype /Link /Rect [${num(link.x)} ${num(link.y)} ${num(
                link.x + link.width,
              )} ${num(link.y + link.height)}] /Border [0 0 0] /A << /S /URI /URI ${literal(
                link.url,
              )} >> >>`,
          )
          .join(" ")}]`
      : "";
    w.object(
      pageId,
      `<< /Type /Page /Parent ${PAGES} 0 R /MediaBox [0 0 ${num(PAGE_WIDTH)} ${num(
        PAGE_HEIGHT,
      )}] /Resources << /Font << /F1 ${fontIds.regular} 0 R /F2 ${fontIds.bold} 0 R >> >> /Contents ${
        pageId + 1
      } 0 R${annots} >>`,
    );
    w.stream(pageId + 1, "", contents[index]!);
  });

  const count = firstPage + pages.length * 2;
  const xref = w.position;
  const rows = ["0000000000 65535 f "];
  for (let id = 1; id < count; id += 1) {
    rows.push(`${String(w.offsets[id] ?? 0).padStart(10, "0")} 00000 n `);
  }
  w.write(
    `xref\n0 ${count}\n${rows.join("\n")}\ntrailer\n<< /Size ${count} /Root ${CATALOG} 0 R /Info ${INFO} 0 R >>\nstartxref\n${xref}\n%%EOF\n`,
  );
  return w.bytes();
}
