"""
Regenerates src/lib/pdf/font-data.ts: the two Inter weights the PDF writer
(src/lib/pdf/document.ts) embeds, subset to the scripts this app is written in.

WHY A SUBSET, AND WHY BAKED IN. The only document this app renders as PDF is
the moderation statement of reasons, in the seller's language, and three of
those languages (cs, pl, sk) need Latin Extended-A. The PDF standard fonts
cannot print "č", "ł" or "ů", and the Inter the dashboard ships
(src/app/fonts/Inter.woff2) is a Latin-only web subset. So the writer embeds
its own TrueType font: Latin, Latin-1, Latin Extended-A and the punctuation
real prose uses, with no hinting and no layout tables. Around 45 KB per
weight, deflated at build time so the writer can embed it without compressing
anything at request time.

Inter is licensed under the SIL Open Font License 1.1, which permits
embedding and redistributing a modified (subset) copy; the copyright and
licence name records are kept inside the font as the licence requires.

RUN (needs uv, https://docs.astral.sh/uv/):

    curl -s "https://fonts.googleapis.com/css2?family=Inter:wght@400;600"
    # download the two .ttf URLs it prints as Inter-400.ttf and Inter-600.ttf
    uvx --with brotli --from fonttools python scripts/build-pdf-font.py \
        Inter-400.ttf Inter-600.ttf src/lib/pdf/font-data.ts
"""

import base64
import io
import sys
import zlib

from fontTools import subset
from fontTools.ttLib import TTFont

UNICODES = (
    list(range(0x0020, 0x007F))  # Basic Latin
    + list(range(0x00A0, 0x0100))  # Latin-1 Supplement
    + list(range(0x0100, 0x0180))  # Latin Extended-A (cs, pl, sk, ...)
    + list(range(0x0218, 0x021C))  # Romanian comma-below letters
    + list(range(0x2010, 0x2016))  # hyphens and dashes
    + list(range(0x2018, 0x201F))  # quotation marks
    + [0x2020, 0x2021, 0x2022, 0x2026, 0x2030, 0x2032, 0x2033, 0x2039, 0x203A]
    + [0x20AC, 0x2116, 0x2122, 0x2192, 0x2212]
)


def build(path: str) -> dict:
    options = subset.Options()
    options.hinting = False
    options.layout_features = []
    options.drop_tables += ["GSUB", "GPOS", "GDEF", "STAT", "gasp", "prep", "DSIG"]
    # Copyright, family, style, unique id, full name, version, PostScript
    # name, licence and licence URL: the OFL asks for the notice and licence
    # to travel with the font.
    options.name_IDs = [0, 1, 2, 3, 4, 5, 6, 13, 14]
    options.notdef_outline = True
    options.recalc_bounds = True

    font = TTFont(path)
    subsetter = subset.Subsetter(options=options)
    subsetter.populate(unicodes=UNICODES)
    subsetter.subset(font)

    buffer = io.BytesIO()
    font.save(buffer)
    raw = buffer.getvalue()

    head = font["head"]
    hhea = font["hhea"]
    os2 = font["OS/2"]
    hmtx = font["hmtx"]
    order = font.getGlyphOrder()
    cmap = font.getBestCmap()

    glyphs = []
    for codepoint in sorted(cmap):
        name = cmap[codepoint]
        glyphs += [codepoint, order.index(name), hmtx[name][0]]

    return {
        "postscript": font["name"].getDebugName(6),
        "unitsPerEm": head.unitsPerEm,
        "ascent": hhea.ascent,
        "descent": hhea.descent,
        "capHeight": getattr(os2, "sCapHeight", hhea.ascent),
        "bbox": [head.xMin, head.yMin, head.xMax, head.yMax],
        "notdefWidth": hmtx[order[0]][0],
        "glyphs": glyphs,
        "length": len(raw),
        "deflated": base64.b64encode(zlib.compress(raw, 9)).decode("ascii"),
    }


def emit(name: str, font: dict) -> str:
    glyphs = ",".join(str(value) for value in font["glyphs"])
    return f"""export const {name}: EmbeddedFont = {{
  postscriptName: "{font['postscript']}",
  unitsPerEm: {font['unitsPerEm']},
  ascent: {font['ascent']},
  descent: {font['descent']},
  capHeight: {font['capHeight']},
  bbox: [{', '.join(str(v) for v in font['bbox'])}],
  notdefWidth: {font['notdefWidth']},
  glyphs: [{glyphs}],
  length: {font['length']},
  deflated:
    "{font['deflated']}",
}};
"""


def main() -> None:
    regular_path, semibold_path, out_path = sys.argv[1:4]
    regular = build(regular_path)
    semibold = build(semibold_path)
    source = (
        "// GENERATED by scripts/build-pdf-font.py. Do not edit by hand.\n"
        "//\n"
        "// Inter (https://rsms.me/inter), Copyright the Inter Project Authors,\n"
        "// licensed under the SIL Open Font License 1.1\n"
        "// (https://openfontlicense.org). Subset to Latin, Latin-1, Latin\n"
        "// Extended-A and common punctuation, unhinted, zlib-deflated.\n"
        "\n"
        'import type { EmbeddedFont } from "./document";\n'
        "\n"
        + emit("INTER_REGULAR", regular)
        + "\n"
        + emit("INTER_SEMIBOLD", semibold)
    )
    with open(out_path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(source)
    print(
        f"wrote {out_path}: regular {regular['length']} bytes "
        f"({len(regular['glyphs']) // 3} glyphs), semibold {semibold['length']} bytes"
    )


if __name__ == "__main__":
    main()
